export const projectsData = {
  'AUPARK-prestresenie-parkovacieho-domu': { name: 'AUPARK - prestrešenie parkovacieho domu', category: 'Priemyselné stavby', description: 'Realizácia prestrešenia parkovacieho domu v objekte AUPARK. Projekt zahŕňal návrh a výrobu oceľovej konštrukcie s moderným dizajnom.', images: ['1.webp','2.webp','3.webp','4.webp','5.webp','6.webp','7.webp','8.webp'] },
  'Balkony-Banska-Bystrica': { name: 'Balkóny Banská Bystrica', category: 'Zámočnícke výrobky', description: 'Výroba a montáž balkónových konštrukcií v Banskej Bystrici. Moderné riešenie s dôrazom na bezpečnosť a estetiku.', images: ['1.webp','2.webp','3.webp','4.webp'] },
  'Chranena-dielna': { name: 'Chránená dielňa', category: 'Oceľové konštrukcie', description: 'Oceľová konštrukcia chránicej dielne s komplexným riešením pracovného priestoru.', images: ['1.webp','2.webp','3.webp'] },
  'Demontaz-zeleznicneho-mosta-Holisa': { name: 'Demontáž železničného mosta Holiša', category: 'Mostné konštrukcie', description: 'Špecializovaná demontáž železničného mosta v Holíši s použitím pokročilých technológií.', images: ['1.webp','2.webp','3.webp','4.webp','5.webp','6.webp','7.webp'] },
  'Dunajska-Streda-Ocelova-konstrukcia-pre-vzduchotechniku': { name: 'Dunajská Streda - Oceľová konštrukcia pre vzduchotechniku', category: 'Oceľové konštrukcie', description: 'Špecializovaná oceľová konštrukcia navrhnutá pre vzduchotechnické zariadenia.', images: ['1.webp'] },
  'Hlohovec-most': { name: 'Hlohovec most', category: 'Mostné konštrukcie', description: 'Kompletná realizácia mostnej konštrukcie v Hlohovci s dôrazom na bezpečnosť a dlhodobú životnosť.', images: ['1.webp','2.webp','3.webp','4.webp','5.webp','6.webp','7.webp','8.webp','9.webp','10.webp','11.webp','12.webp','13.webp','14.webp'] },
  'IKEA-Bratislava-pilon': { name: 'IKEA Bratislava - pilón', category: 'Oceľové konštrukcie', description: 'Realizácia reklamného pilónu pre IKEA Bratislava s moderným dizajnom a vysokou kvalitou spracovania.', images: ['1.webp','2.webp','3.webp','4.webp'] },
  'KFC-Banska-Bystrica': { name: 'KFC Banská Bystrica', category: 'Komerčné stavby', description: 'Kompletná realizácia oceľovej konštrukcie reštaurácie KFC v Banskej Bystrici.', images: ['1.webp','2.webp','3.webp','4.webp','5.webp','6.webp','7.webp','8.webp','9.webp','10.webp','11.webp'] },
  'Montaz-mosta-v-Rajcianke': { name: 'Montáž mosta v Rajčianke', category: 'Mostné konštrukcie', description: 'Profesionálna montáž mostnej konštrukcie v Rajčianke s dodržaním všetkých bezpečnostných štandardov.', images: ['1.webp','2.webp','3.webp','4.webp','5.webp'] },
  'Ocelove-prvky-k-predpetiu-mosta-Kysucke-Nove-Mesto': { name: 'Oceľové prvky k predpetiu mosta - Kysucké Nové Mesto', category: 'Mostné konštrukcie', description: 'Výroba a dodávka špecializovaných oceľových prvkov pre predpätie mostnej konštrukcie.', images: ['1.webp','2.webp','3.webp'] },
  'Plosina-DOKA-DREVO': { name: 'Plošina DOKA DREVO', category: 'Oceľové konštrukcie', description: 'Špecializovaná oceľová plošina pre manipuláciu s drevom v spoločnosti DOKA DREVO.', images: ['1.webp','2.webp','3.webp','4.webp'] },
  'Prestresenie-rampy': { name: 'Prestrešenie rampy', category: 'Oceľové konštrukcie', description: 'Návrh a realizácia prestrešenia nakládacej rampy s moderným dizajnom a funkčnosťou.', images: ['1.webp','2.webp'] },
  'Presun-protitankovej-steny': { name: 'Presun protitankovej steny', category: 'Špeciálne projekty', description: 'Špecializovaný projekt presunu historických protitankových zábran s použitím ťažkej techniky.', images: ['1.webp','2.webp','3.webp','4.webp','5.webp','6.webp','7.webp'] },
  'Pristavba-SAD-Banska-Bystrica': { name: 'Prístavba SAD Banská Bystrica', category: 'Priemyselné stavby', description: 'Realizácia prístavby pre Slovenskú autobusovú dopravu v Banskej Bystrici.', images: ['1.webp','2.webp','3.webp','4.webp'] },
  'Pristresok-pre-agrotechniku-Dolna-Streda': { name: 'Prístrešok pre agrotechniku Dolná Streda', category: 'Oceľové konštrukcie', description: 'Praktické riešenie prístrešku pre poľnohospodársku techniku s odolnou oceľovou konštrukciou.', images: ['1.webp','2.webp','3.webp','4.webp'] },
  'Pristresok-pre-rozvadzac': { name: 'Prístrešok pre rozvádzač', category: 'Oceľové konštrukcie', description: 'Ochranný prístrešok pre elektrický rozvádzač s antikuróznou úpravou.', images: ['1.webp'] },
  'Protihlukova-stena-Bratislava': { name: 'Protihluková stena Bratislava', category: 'Protihluková ochrana', description: 'Inštalácia protihlukových stien v Bratislave pre zníženie hluku z dopravy.', images: ['1.webp','2.webp'] },
  'Protihlukova-stena-Mirotice-CR': { name: 'Protihluková stena - Mirotice, ČR', category: 'Protihluková ochrana', description: 'Realizácia protihlukových bariér v Miroticiach, Česká republika.', images: ['1.webp','2.webp','3.webp','4.webp','5.webp','6.webp','7.webp'] },
  'Protihlukova-stena-ZSR-Trencin': { name: 'Protihluková stena ŽSR Trenčín', category: 'Protihluková ochrana', description: 'Protihluková ochrana pre železničnú trať v Trenčíne v spolupráci so Železnicami SR.', images: ['1.webp'] },
  'Rampy-Bezrucova-Bratislava': { name: 'Rampy Bezručova, Bratislava', category: 'Oceľové konštrukcie', description: 'Výroba a montáž nakládacích rámp na Bezručovej ulici v Bratislave.', images: ['1.webp','2.webp','3.webp','4.webp'] },
  'STK-Banska-Bystrica': { name: 'STK Banská Bystrica', category: 'Komerčné stavby', description: 'Realizácia oceľovej konštrukcie pre stanicu technickej kontroly v Banskej Bystrici.', images: ['1.webp','2.webp','3.webp','4.webp','5.webp'] },
  'Technicko-hygienicka-udrzba-zeleznicnych-kolajovych-vozidiel-Humenne': { name: 'Technicko-hygienická údržba železničných koľajových vozidiel - Humenné', category: 'Priemyselné stavby', description: 'Špecializované zariadenie pre údržbu železničných vozidiel v Humennom.', images: ['1.webp','2.webp','3.webp','4.webp','5.webp','6.webp'] },
  'Teplaren-Stefe-Banska-Bystrica': { name: 'Tepláreň Stefe Banská Bystrica', category: 'Priemyselné stavby', description: 'Realizácia oceľových konštrukcií pre tepláreň Stefe v Banskej Bystrici.', images: ['1.webp','2.webp','3.webp','4.webp','5.webp','6.webp','7.webp'] },
  'Trolejbusove-DEPO-Zilina-Technologicke-plosiny': { name: 'Trolejbusové DEPO Žilina - Technologické plošiny s automatizovaným výsuvom', category: 'Priemyselné stavby', description: 'Pokročilé technologické plošiny s automatizovaným výsuvom pre trolejbusové depo v Žiline.', images: ['1.webp','2.webp','3.webp','4.webp','5.webp','6.webp','7.webp','8.webp','9.webp'] },
  'Trolejbusove-DEPO-Zilina': { name: 'Trolejbusové DEPO Žilina', category: 'Priemyselné stavby', description: 'Kompletná realizácia oceľovej konštrukcie trolejbusového depa v Žiline.', images: ['1.webp','2.webp','3.webp','4.webp','5.webp','6.webp','10.webp','11.webp','12.webp','13.webp','14.webp','15.webp','16.webp','17.webp','18.webp','19.webp','20.webp','21.webp','22.webp','23.webp','24.webp'] },
  'Ustredna-vojenska-nemocnica-Ruzomberok': { name: 'Ústredná vojenská nemocnica - Ružomberok', category: 'Verejné stavby', description: 'Realizácia oceľových konštrukcií pre vojenskú nemocnicu v Ružomberku.', images: ['1.webp','2.webp','3.webp','4.webp','5.webp','6.webp','7.webp','8.webp','9.webp','10.webp','11.webp'] },
  'Viglas-oplotenie': { name: 'Vígľaš - oplotenie', category: 'Zámočnícke výrobky', description: 'Realizácia moderného oplotenia vo Vígľaši s estetickým a funkčným dizajnom.', images: ['1.webp','2.webp','3.webp','4.webp','5.webp'] },
  'Viglas-pristavba-haly': { name: 'Vígľaš - prístavba haly', category: 'Oceľové konštrukcie', description: 'Prístavba priemyselnej haly vo Vígľaši s oceľovou konštrukciou.', images: ['1.webp','2.webp','3.webp','4.webp'] },
  'Vojenske-historicke-muzeum-Piestany': { name: 'Vojenské historické múzeum - Piešťany', category: 'Verejné stavby', description: 'Oceľové konštrukcie pre expozície vojenského historického múzea v Piešťanoch.', images: ['1.webp','2.webp','3.webp','4.webp','5.webp','6.webp','7.webp'] },
  'Zabradlie-rodinny-dom': { name: 'Zábradlie rodinný dom', category: 'Zámočnícke výrobky', description: 'Elegantné zábradlie pre rodinný dom s moderným dizajnom a vysokou kvalitou spracovania.', images: ['1.webp','2.webp','3.webp','4.webp','5.webp','6.webp','7.webp','8.webp','9.webp','10.webp'] },
};

// Order shown on /referencie
export const referencieOrder = [
  'Trolejbusove-DEPO-Zilina-Technologicke-plosiny',
  'Montaz-mosta-v-Rajcianke',
  'Demontaz-zeleznicneho-mosta-Holisa',
  'Plosina-DOKA-DREVO',
  'Balkony-Banska-Bystrica',
  'Rampy-Bezrucova-Bratislava',
  'Presun-protitankovej-steny',
  'Protihlukova-stena-Mirotice-CR',
  'Ocelove-prvky-k-predpetiu-mosta-Kysucke-Nove-Mesto',
  'Trolejbusove-DEPO-Zilina',
  'KFC-Banska-Bystrica',
  'Vojenske-historicke-muzeum-Piestany',
  'Dunajska-Streda-Ocelova-konstrukcia-pre-vzduchotechniku',
  'Pristavba-SAD-Banska-Bystrica',
  'Viglas-oplotenie',
  'Technicko-hygienicka-udrzba-zeleznicnych-kolajovych-vozidiel-Humenne',
  'Protihlukova-stena-Bratislava',
  'Zabradlie-rodinny-dom',
  'Hlohovec-most',
  'Viglas-pristavba-haly',
  'Ustredna-vojenska-nemocnica-Ruzomberok',
  'IKEA-Bratislava-pilon',
  'Pristresok-pre-rozvadzac',
  'AUPARK-prestresenie-parkovacieho-domu',
  'Prestresenie-rampy',
  'Pristresok-pre-agrotechniku-Dolna-Streda',
  'Chranena-dielna',
  'Teplaren-Stefe-Banska-Bystrica',
  'STK-Banska-Bystrica',
  'Protihlukova-stena-ZSR-Trencin',
];
