export const serviceLinks = [
  { slug: 'ocelove-konstrukcie', label: 'Oceľové konštrukcie', bg: '/sources/referencie/IKEA-Bratislava-pilon/2.webp' },
  { slug: 'zamocnicke-vyrobky', label: 'Zámočnícke výrobky', bg: '/sources/referencie/Zabradlie-rodinny-dom/1.webp' },
  { slug: 'povrchova-uprava', label: 'Povrchová úprava', bg: '/sources/povrch.webp' },
  { slug: 'oplastenie-konstrukcii', label: 'Opláštenie konštrukcií', bg: '/sources/referencie/Trolejbusove-DEPO-Zilina/17.webp' },
  { slug: 'klampiarske-prace', label: 'Klampiarske práce', bg: '/sources/klamp.webp' },
  { slug: 'predaj-hutnickeho-materialu', label: 'Predaj hutníckeho materiálu', bg: '/sources/steel.webp' },
];

export const services = {
  'ocelove-konstrukcie': {
    title: 'Oceľové konštrukcie',
    heroImg: '/sources/referencie/IKEA-Bratislava-pilon/2.webp',
    imgAlt: 'Oceľové konštrukcie',
    lead: 'Zaisťujeme návrh oceľovej konštrukcie podľa požiadaviek investora. Kladieme dôraz na dodržanie noriem kvality, aby boli konštrukcie čo najekonomickejšie, s dostatočnou pevnosťou a čo najväčšou estetickou pridanou hodnotou.',
    leadBlocks: [
      { type: 'h2', text: 'Typy dodávaných oceľových konštrukcií' },
      { type: 'p', text: 'Podľa tvaru a rozmeru použitého materiálu, alebo spôsobu výroby existujú tieto základné typy oceľových konštrukcií:' },
      { type: 'ul', items: ['rámové konštrukcie', 'priehradové konštrukcie', 'zvárané konštrukcie', 'ostatné špecifické konštrukcie'] },
      { type: 'h2', text: 'Možnosti použitia oceľových konštrukcií' },
      { type: 'p', text: 'Oceľové konštrukcie majú široké spektrum využitia vo výrobných aj nevýrobných odvetviach národného hospodárstva.' },
    ],
    fullBlocks: [
      { type: 'twoColumns', left: { title: 'Použitie v rámci výrobných odvetví:', items: ['priemyselné haly','výrobné haly','skladové haly','poľnohospodárske objekty','mosty a časti cestnej infraštruktúry','protihlukové steny','technologické konštrukcie a plošiny','žeriavové dráhy','oceľové stĺpy a stožiare'] }, right: { title: 'Použitie v rámci nevýrobných odvetví:', items: ['nákupné centrá','športové haly','telocvične','parkovacie domy','administratívne budovy','obchodné prevádzky','servisy a autodielne','autosalóny'] } },
      { type: 'h2', text: 'Oceľ ako stavebný materiál' },
      { type: 'p', text: 'Oceľ je najpoužívanejší konštrukčný materiál. Existujú materiály tvrdšie, pevnejšie, odolnejšie, žiaruvzdornejšie. Ale žiadny z nich nemá také vyvážené vlastnosti ako sú tvrdosť, pružnosť, pevnosť, jednoduchosť obrábania a recyklovania.' },
      { type: 'p', text: 'Prednosťou konštrukčnej ocele je jej homogenita a možnosť veľkej tvarovej variability pri zachovaní vysokej výrobnej presnosti.' },
      { type: 'p', text: 'Hlavnou výhodou využitia oceľových konštrukcií je ich vysoká pevnosť vzhľadom k hmotnosti. Preto majú oceľové konštrukcie široké využitie v priemyselnej výstavbe, kde je kladený vysoký dôraz predovšetkým na presnosť, rýchlosť postupu montáže s minimom technologických prestávok, odstránenie sezónnosti, adaptibilita a možnosť ich rekonštrukcie.' },
      { type: 'p', text: 'Nezabúdajme ani na otázku životného prostredia. Oceľové konštrukcie, ako aj odpadový materiál z nich, je takmer na 100% recyklovateľný, čo tvorí zásadnú hodnotu pri otázke udržateľného rozvoja.' },
      { type: 'h2', text: 'Navrhovanie oceľových konštrukcií' },
      { type: 'p', text: 'Kvalitné projekty a technicky progresívne riešenia sú pre firmu Stavomontáže, Kovo-Sklo s.r.o. štandardom. Zaisťujeme návrh oceľovej konštrukcie podľa požiadaviek investora.' },
      { type: 'p', text: 'Oceľové konštrukcie navrhujeme vo všetkých stupňoch projektovej dokumentácie. Súčasťou odbornej podpory je aj návrh pomocných konštrukcií a technologický postup výstavby. Riešime nielen konečný tvar oceľových konštrukcií, ale často aj náročný a komplikovaný postup montáže, zdvíhania a manipulácie s ťažkými a veľkými dielmi.' },
      { type: 'p', text: 'Zabezpečujeme tiež znaleckú a konzultačnú činnosť.' },
      { type: 'p', text: 'Rozmerový návrh a nadimenzovanie konštrukcie vychádza zo statických výpočtov autorizovaného statika. Výpočty sa prevádzajú na základe platných noriem a eurokódov.' },
      { type: 'p', text: 'Výrobná a montážna dokumentácia je vypracovaná podľa statického výpočtu konštrukcie. Používajú sa na to 3D programy Tekla Structures alebo Advance Steel.' },
      { type: 'h2', text: 'Výroba oceľových konštrukcií' },
      { type: 'p', text: 'V našom závode v Banskej Bystrici zabezpečujeme výrobu všetkých druhov oceľových konštrukcií. Vlastnú výrobu máme od založenia spoločnosti. Neustále sa snažíme rozvíjať výrobný program a zvyšovať výrobné kapacity.' },
      { type: 'p', text: 'Výroba oceľových konštrukcií je riadená v súlade s normou EN 1090-1+A1:2001 v triede prevedenia EXC2 alebo EXC3.' },
      { type: 'p', text: 'Kvalita výroby je monitorovaná podľa kontrolných a skúšobných plánov schválených štátnymi normami a predpismi.' },
      { type: 'h2', text: 'Montáž oceľových konštrukcií' },
      { type: 'p', text: 'Montáž oceľových konštrukcií prevádzajú montážni pracovníci našej spoločnosti, prípadne nami overené a vybrané externé montážne skupiny. Všetci montážnici sú spôsobilí a kompetentní vykonávať montážne práce.' },
      { type: 'p', text: 'Kvalitná projektová dokumentácia a dlhoročné skúsenosti týchto pracovníkov zaistia efektívnu výstavbu oceľových konštrukcií s vysokou mierou spoľahlivosti a kvality.' },
      { type: 'p', text: 'Montáž oceľových konštrukcií sa prevádza pomocou vhodne zvolených zdvíhacích a manipulačných prostriedkov (žeriavy, plošiny). Rozmery a hmotnosť montovaných častí oceľovej konštrukcie sú určujúce pri výbere typu a únosnosti týchto zariadení.' },
    ],
    cta: 'Potrebujete oceľové konštrukcie?',
  },
  'zamocnicke-vyrobky': {
    title: 'Zámočnícke výrobky',
    heroImg: '/sources/referencie/Zabradlie-rodinny-dom/2.webp',
    imgAlt: 'Zámočnícke výrobky',
    lead: 'Zámočnícke výrobky tvoria významnú časť výrobného programu firmy Stavomontáže, Kovo-Sklo s.r.o. Špecializujeme sa na výrobu kvalitných kovových prvkov pre priemyselné aj súkromné účely.',
    leadBlocks: [
      { type: 'h2', text: 'Možnosti použitia zámočníckych výrobkov' },
      { type: 'h2', text: 'Použitie v rámci individuálnej a súkromnej výstavby:' },
      { type: 'ul', items: ['zábradlia a ploty', 'schody', 'oceľové brány a dvere', 'prístrešky a markízy'] },
      { type: 'h2', text: 'Použitie v rámci priemyselnej výstavby:' },
      { type: 'ul', items: ['priemyselné schodiská a zábradlia', 'technologické plošiny', 'konštrukcie pre kotvenie technológií a rozvodov', 'požiarne rebríky'] },
    ],
    fullBlocks: [
      { type: 'h2', text: 'Rozdelenie zámočníckych výrobkov' },
      { type: 'p', text: 'Zámočnícke výrobky tvoria významnú časť výrobného programu firmy Stavomontáže, Kovo-Sklo s.r.o.' },
      { type: 'p', text: 'Môžu to byť samostatné výrobky z ocele pre individuálnych zákazníkov, kde slúžia ako bezpečnostný a estetický doplnok rôznych stavieb. Vhodným architektonickým návrhom tvaru a povrchovej úpravy môžu byť určujúce pre konečný dizajn investičného zámeru.' },
      { type: 'p', text: 'V priemyselnej výstavbe tvoria zámočnícke výrobky významný technologický alebo estetický doplnok ku hlavným konštrukciám rôznych objektov a zariadení.' },
      { type: 'p', text: 'Výroba zámočníckych konštrukcií prebieha v našom výrobnom areáli a je riadená v súlade s normou EN 1090-1+A1:2001 v triede prevedenia EXC2 alebo EXC3.' },
    ],
    cta: 'Potrebujete zámočnícke výrobky?',
  },
  'povrchova-uprava': {
    title: 'Povrchová úprava',
    heroImg: '/sources/povrch.webp',
    imgAlt: 'Povrchová úprava',
    lead: 'Povrchová úprava je súhrn technologických procesov ktorými sa mení povrch oceľovej konštrukcie tak, aby sa upravili jeho povrchovo - mechanické vlastnosti, odolnosť voči prostrediu alebo dizajn.',
    leadBlocks: [
      { type: 'h2', text: 'Typy povrchovej úpravy' },
      { type: 'ul', items: ['antikorózne nátery', 'práškové lakovanie', 'žiarové zinkovanie', 'protipožiarna ochrana'] },
      { type: 'h2', text: 'Základná definícia' },
      { type: 'p', text: 'Povrchová úprava je súhrn technologických procesov ktorými sa mení povrch oceľovej konštrukcie tak, aby sa upravili jeho povrchovo - mechanické vlastnosti, odolnosť voči prostrediu alebo dizajn.' },
      { type: 'p', text: 'Vhodnou úpravou povrchu výrobku sa výrazne predlžuje jeho životnosť.' },
    ],
    fullBlocks: [
      { type: 'h2', text: 'Príprava povrchu' },
      { type: 'p', text: 'Pred samotnou finálnou povrchovou úpravou je potrebné previesť dokonalé očistenie povrchu oceľových prvkov. Najkvalitnejšia a najrozšírenejšia metóda je otryskávanie. Najštandardnejšou hodnotou používanou pre otryskávanie je hodnota Sa = 2,5.' },
      { type: 'h2', text: 'Antikorózne nátery' },
      { type: 'p', text: 'Naša spoločnosť využíva na ochranu oceľových konštrukcií metódu vysokotlakového nanášania „mokrých" náterových hmôt pomocou vysokotlakového zariadenia.' },
      { type: 'p', text: 'Hrúbka náteru sa pohybuje v rozmedzí od 80 μm do 240 μm podľa požadovanej koróznej triedy. Používame syntetické, epoxidové, akrylátové alebo polyuretánové náterové látky.' },
      { type: 'h2', text: 'Práškové lakovanie' },
      { type: 'p', text: 'Práškovanie, resp. laikmi nesprávne označované ako „komaxitovanie" je najmladšia technológia povrchovej úpravy. Prášková farba sa vypaľuje pri teplote 180 – 200°C, kedy dochádza k roztavenie na povrchu výrobku a k vytvoreniu homogénneho náteru.' },
      { type: 'h2', text: 'Žiarové zinkovanie' },
      { type: 'p', text: 'Pre oceľové konštrukcie vystavené poveternostným vplyvom je najvhodnejší spôsob povrchovej úpravy žiarové zinkovanie. Princíp spočíva v ponorení oceľového dielca do vane s taveninou zinku o teplote okolo 450 °C.' },
      { type: 'h2', text: 'Protipožiarna ochrana' },
      { type: 'p', text: 'Aplikujeme na oceľové prvky protipožiarny náter podľa stanovenej požiarnej odolnosti. Účinkom ohňa tento náter napeňuje a vytvára izolačnú vrstvu. Protipožiarnymi nátermi sa dosahuje požiarna odolnosť v rozsahu od R15 do R90.' },
    ],
    cta: 'Potrebujete povrchovú úpravu?',
  },
  'oplastenie-konstrukcii': {
    title: 'Opláštenie oceľových konštrukcií',
    heroImg: '/sources/referencie/Trolejbusove-DEPO-Zilina/17.webp',
    imgAlt: 'Opláštenie oceľových konštrukcií',
    lead: 'Najčastejším využitím oceľových konštrukcií v priemyselnom stavebníctve sú oceľové haly. Zabezpečujeme kompletné opláštenie oceľových konštrukcií kvalitnými materiálmi s dlhou životnosťou.',
    leadBlocks: [
      { type: 'p', text: 'Najčastejším využitím oceľových konštrukcií v priemyselnom stavebníctve sú oceľové haly. Na strešné a stenové opláštenie sa používajú rôzne systémy podľa požiadaviek na tepelno-technické, požiarne a dizajnové vlastnosti samotného opláštenia.' },
      { type: 'h2', text: 'Strešné opláštenie' },
      { type: 'ul', items: ['strešný trapézový plech (nezateplené objekty)','strešný skladaný plášť (nosný trapézový plech, tepelná izolácia, hydroizolácia)','sendvičové panely (s výplňou PUR, PIR, minerálna vlna)','strešné presvetlenia (polykarbonátové pásy, strešné svetlíky)'] },
    ],
    fullBlocks: [
      { type: 'p', text: 'Podľa typu a smerovej orientácie opláštenia sa na oceľovej konštrukcii pripravia potrebné kotviace prvky. Sú to napr. väznice, vodorovné konštrukčné vzpery (paždíky) a výmeny na otvory v opláštení. Používajú sa na to valcované profily (U, JP, L), alebo tenkostenné pozinkované profily (Z, U, napr. Metsec).' },
      { type: 'h2', text: 'Stenové opláštenie' },
      { type: 'ul', items: ['stenový trapézový plech (nezateplené objekty)','sendvičové panely (s výplňou PUR, PIR, minerálna vlna)','stenový skladaný plášť (C-kazeta, izolácia, trapézový plech)','výplne otvorov (brány, dvere, okná, polykarbonátové pásy)'] },
    ],
    cta: 'Potrebujete opláštenie oceľových konštrukcií?',
  },
  'klampiarske-prace': {
    title: 'Klampiarske práce',
    heroImg: '/sources/klamp.webp',
    imgAlt: 'Klampiarske práce',
    lead: 'Klampiarske prvky používame ako ochranný, funkčný a estetický doplnok pre opláštenie oceľových konštrukcií. Zabezpečujeme komplexné klampiarske práce pre všetky typy stavieb.',
    leadBlocks: [
      { type: 'p', text: 'Klampiarske prvky používame ako ochranný, funkčný a estetický doplnok pre opláštenie oceľových konštrukcií. Sú to napríklad parapetné lišty, rohové lišty, omega lišty, strešný hrebenáč, záveterné lišty, odkvapové lišty, lemovanie lišty a podobne.' },
      { type: 'p', text: 'Vyrábajú sa v našej klampiarskej dielni. Sme vybavení viacerými zariadeniami na ktorých sa prevádza strihanie, ohraňovanie, ohýbanie a zakružovanie plechov všetkých rozmerov a hrúbok.' },
    ],
    fullBlocks: [],
    cta: 'Potrebujete klampiarske práce?',
  },
  'predaj-hutnickeho-materialu': {
    title: 'Predaj hutníckeho materiálu',
    heroImg: '/sources/steel.webp',
    imgAlt: 'Hutnícky materiál',
    lead: 'Predaj hutníckeho materiálu a plechov. Ponúkame široký sortiment oceľových profilov pre všetky potreby stavebníctva a priemyslu s možnosťou dodania priamo na stavbu.',
    leadBlocks: [
      { type: 'p', text: 'Naša spoločnosť ponúka aj predaj hutníckeho materiálu a plechov. Ponúkame široký sortiment oceľových profilov v štandardných dĺžkach 6 a 12 metrov a plechov s rozmermi tabúľ 1m x 2m, 1,25m x 2,5m, 1,5m x 3m a 2m x 6m.' },
      { type: 'p', text: 'Materiál Vám v prípade záujmu vieme upraviť na požadované dĺžky a rozmery.' },
    ],
    fullBlocks: [],
    cta: 'Potrebujete hutnícky materiál?',
  },
};
